# push_image.yml
name: 'Push docker images'
description: 'Pushing Docker image to Container Registry'
inputs:
  
  cr_servername:
    required: true
  cr_username:
    required: false
  cr_password:
    required: flase
   
    
runs:
  using: "composite"
  steps:
    - run: ls -lart
      shell: bash
    - run : echo $RUNNER_NAME $RUNNER_OS $RUNNER_ARCH $RUNNER_TEMP
      shell: bash

    - uses: Azure/docker-login@v1
      with:
        username: ${{inputs.cr_username}}
        password: ${{inputs.cr_password}}
        login-server: ${{inputs.cr_servername}}  
      if: ${{ !contains(inputs.cr_servername, 'ghcr.io')  }}
      
